<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>Sink</AssemblyName>
    <RootNamespace>Sink</RootNamespace>
    <Version>0.5.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Clickwheel" Version="0.1.1" />
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="2.1.13" />
    <PackageReference Include="System.Management" Version="10.0.12" />
    <PackageReference Include="TagLibSharp" Version="2.3.0" />
  </ItemGroup>
</Project>
